/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica que el servidor responde */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description El servidor está vivo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            estado?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra un usuario
         * @description Registrarse deja la sesión abierta: la respuesta trae la cookie. Pedir
         *     las credenciales otra vez inmediatamente después no informa nada.
         *
         *     El usuario no es el perfil profesional. Para atender hay que crear
         *     además un perfil con `POST /api/v1/profesionales`; para reservar
         *     turnos no hace falta.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionRegistro"];
                };
            };
            responses: {
                /** @description Creado, con la sesión abierta */
                201: {
                    headers: {
                        /** @description Cookie de sesión `HttpOnly`, `SameSite=Lax`, 7 días */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                409: components["responses"]["EmailEnUso"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Devuelve el usuario de la sesión
         * @description `perfilProfesionalId` es lo único que el cliente necesita para saber
         *     si mostrar la vista de profesional o la de paciente. Es derivado: no
         *     hay ningún campo de rol, justamente para que no pueda desincronizarse
         *     del perfil real.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description El usuario autenticado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsuarioActual"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia sesión
         * @description El 401 es idéntico para "ese email no existe" y "esa contraseña está
         *     mal", a propósito: distinguirlos convertiría a este endpoint en un
         *     oráculo de qué direcciones están registradas.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionLogin"];
                };
            };
            responses: {
                /** @description Sesión abierta */
                201: {
                    headers: {
                        /** @description Cookie de sesión `HttpOnly`, `SameSite=Lax`, 7 días */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["CredencialesInvalidas"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesiones/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cierra la sesión
         * @description Idempotente: 204 también sin sesión. Un cliente que reintenta no está
         *     haciendo nada malo, y decirle "no estabas logueado" no le sirve.
         *
         *     La sesión se borra del servidor de verdad, no solo se vence la cookie.
         *     Es la razón por la que el token es opaco y no un JWT.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión cerrada */
                204: {
                    headers: {
                        /** @description La cookie de sesión vencida */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mis turnos como paciente
         * @description Devuelve los turnos del usuario de la sesión, cancelados incluidos.
         *
         *     **No acepta un `pacienteId` como filtro**, a propósito: el paciente es
         *     siempre el de la sesión. Aceptarlo convertiría este endpoint en una
         *     forma de leer la agenda de cualquiera.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Opcional, AAAA-MM-DD, igual que en `/bloqueos`. Sin rango se
                     *     devuelven los vigentes y futuros.
                     */
                    desde?: string;
                    /** @description Opcional, AAAA-MM-DD. El día pedido entra entero. */
                    hasta?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Los turnos del paciente, con el profesional de cada uno */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaTurnosDePaciente"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/turnos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancela un turno
         * @description Lo pueden hacer **las dos partes**: el paciente y el profesional. Por eso
         *     la ruta no cuelga de `/profesionales/{id}` — no es una operación del
         *     dueño de la agenda.
         *
         *     No es idempotente: cancelar un turno ya cancelado da 422. A diferencia
         *     del logout, repetir la operación probablemente significa que el cliente
         *     cree algo distinto de lo que pasó.
         *
         *     Un turno que ya empezó tampoco se cancela: reescribirlo hacia atrás
         *     borraría el registro de una consulta que ocurrió.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Turno cancelado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista profesionales
         * @description Por defecto devuelve solo los activos. Para ver los dados de baja hay
         *     que pedir `estado=inactivo` explícitamente.
         */
        get: {
            parameters: {
                query?: {
                    especialidad?: components["schemas"]["Especialidad"];
                    /** @description Compara sin distinguir mayúsculas ni acentos */
                    zona?: string;
                    estado?: components["schemas"]["Estado"];
                    /**
                     * @description Busca en nombre y apellido, sin distinguir mayúsculas ni acentos.
                     *     Buscar `gonzalez` encuentra a `González`.
                     */
                    busqueda?: string;
                    /**
                     * @description Un valor por encima del máximo no se rechaza: se recorta al
                     *     máximo, y `paginacion.limite` en la respuesta informa el que de
                     *     verdad se aplicó. Paginar sumando el valor pedido en vez del
                     *     devuelto saltea registros.
                     */
                    limite?: number;
                    desplazamiento?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaProfesionales"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
            };
        };
        put?: never;
        /**
         * Da de alta un profesional
         * @description El profesional nace con `estado: activo` y `verificacion: pendiente`.
         *     Nadie nace verificado: la verificación es un acto contra REFEPS que
         *     todavía no está implementado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionProfesional"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        /** @description URL del recurso creado */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profesional"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                409: components["responses"]["Conflicto"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Trae un profesional por ID
         * @description Un profesional dado de baja devuelve 200 con `estado: inactivo`. El
         *     recurso existe, simplemente no opera.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profesional"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        /**
         * Reemplaza los campos editables
         * @description Reemplazo total, no parcial. `id`, `slug`, `estado`, `verificacion` y
         *     las marcas de tiempo no son editables.
         *
         *     El slug no se regenera al cambiar el nombre: es una URL pública y
         *     romperla rompe enlaces y posicionamiento.
         *
         *     Cambiar la matrícula o la especialidad devuelve `verificacion` a
         *     `pendiente`: la verificación se hizo sobre esos datos.
         *
         *     Funciona sobre profesionales inactivos y no cambia su estado.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionProfesional"];
                };
            };
            responses: {
                /** @description Actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profesional"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        post?: never;
        /**
         * Da de baja al profesional
         * @description Baja lógica, no borrado. Pone `estado` en `inactivo` y sella
         *     `dadoDeBajaEn`. El registro se queda: los turnos y comprobantes
         *     históricos apuntan a él.
         *
         *     Es idempotente: dar de baja algo ya dado de baja devuelve 204.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dado de baja */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/reactivar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revierte la baja
         * @description Idempotente. Sobre alguien ya activo devuelve 200 sin cambios.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reactivado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profesional"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfiles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /**
         * Trae el perfil público de un profesional por su slug
         * @description Es lo que consume la página `/p/{slug}` del frontend. Vive en su
         *     propio recurso, distinto de `profesionales`, porque es de lectura
         *     pública y no expone lo administrativo del CRUD.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profesional"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/horarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** El horario semanal del profesional */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaHorarios"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        /**
         * Reemplaza el horario semanal completo
         * @description Reemplazo total: la semana se edita como una unidad. Una lista vacía
         *     deja al profesional sin horarios, que es legítimo.
         *
         *     Se rechaza con 422 si dos bloques del mismo día se solapan, si en algún
         *     bloque no entra ninguna sesión, o si algún bloque usa una modalidad que
         *     el profesional no declara ofrecer.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionHorarios"];
                };
            };
            responses: {
                /** @description La semana resultante, ordenada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaHorarios"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/bloqueos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Los bloqueos del profesional
         * @description Sin `desde` ni `hasta` devuelve los vigentes y futuros. Con rango,
         *     devuelve los que lo pisan, aunque sea en parte.
         */
        get: {
            parameters: {
                query?: {
                    desde?: string;
                    hasta?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaBloqueos"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        /** Bloquea un rango de la agenda */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionBloqueo"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        /** @description URL del recurso creado */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BloqueoCreado"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/bloqueos/{bloqueoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                bloqueoId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Elimina un bloqueo
         * @description El bloqueo tiene que ser de ese profesional. Borrar el de otro desde
         *     esta ruta es un 404.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    bloqueoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/huecos": {
        parameters: {
            query: {
                desde: string;
                hasta: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Los huecos reservables del profesional
         * @description `desde` y `hasta` son fechas y las dos entran: del 25 al 27 incluye los
         *     tres días.
         *
         *     `hasta` anterior a `desde` es 400: es un query param mal formado, no
         *     una entidad semánticamente inválida.
         *
         *     El rango se recorta al horizonte del profesional, no se rechaza, y
         *     `rango` en la respuesta informa el que de verdad se usó. También se
         *     recorta hacia atrás: pedir una fecha pasada nunca produce huecos, así
         *     que `desde` nunca queda antes de hoy.
         *
         *     Un profesional dado de baja devuelve una lista vacía, no un error.
         */
        get: {
            parameters: {
                query: {
                    desde: string;
                    hasta: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaHuecos"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                404: components["responses"]["NoEncontrado"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profesionales/{id}/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * La agenda ocupada del profesional
         * @description **Privado, a diferencia de `/horarios` y `/bloqueos`.** La asimetría es
         *     deliberada: los huecos libres son información de oferta y son públicos,
         *     pero la agenda *ocupada* dice quién es paciente de quién, y eso es dato
         *     de salud bajo Ley 25.326.
         *
         *     Solo lo responde el dueño del perfil.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Opcional, AAAA-MM-DD, igual que en `/bloqueos`. Sin rango se
                     *     devuelven los vigentes y futuros.
                     */
                    desde?: string;
                    /** @description Opcional, AAAA-MM-DD. El día pedido entra entero. */
                    hasta?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description La agenda del profesional, con el paciente de cada turno */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListaTurnosDeProfesional"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                403: components["responses"]["NoAutorizado"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        /**
         * Reserva un turno
         * @description El paciente sale de la sesión, nunca del cuerpo.
         *
         *     El `inicio` tiene que coincidir exactamente con un hueco libre de
         *     `GET .../huecos`. Si dos pacientes piden el mismo al mismo tiempo, el
         *     segundo recibe 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PeticionTurno"];
                };
            };
            responses: {
                /** @description Turno reservado */
                201: {
                    headers: {
                        /** @description URL del turno creado */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Turno"];
                    };
                };
                400: components["responses"]["PeticionInvalida"];
                401: components["responses"]["NoAutenticado"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["TurnoNoDisponible"];
                413: components["responses"]["CuerpoDemasiadoGrande"];
                415: components["responses"]["TipoDeContenidoInvalido"];
                422: components["responses"]["ValidacionFallida"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PeticionRegistro: {
            /**
             * Format: email
             * @example juan@ejemplo.com
             */
            email: string;
            /**
             * Format: password
             * @description Mínimo 8 caracteres, el piso de NIST SP 800-63B. El máximo son 72
             *     **bytes**, no caracteres: bcrypt descarta en silencio todo lo que
             *     pase de ahí, y con acentos el byte 72 llega antes.
             *
             *     Sin reglas de composición a propósito: alargan el formulario sin
             *     agregar entropía real.
             */
            contrasena: string;
            /** @example Juan */
            nombre: string;
            /** @example Pérez */
            apellido: string;
        };
        PeticionLogin: {
            /**
             * Format: email
             * @example juan@ejemplo.com
             */
            email: string;
            /** Format: password */
            contrasena: string;
        };
        /**
         * @description La identidad de login. Nunca incluye el hash de la contraseña ni el
         *     token de sesión: el token viaja solo en el `Set-Cookie`.
         */
        Usuario: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            nombre: string;
            apellido: string;
            /** Format: date-time */
            creadoEn: string;
        };
        UsuarioActual: components["schemas"]["Usuario"] & {
            /**
             * Format: uuid
             * @description El perfil profesional del usuario, o `null` si no tiene. No
             *     tener perfil es normal: es la mitad de los usuarios.
             */
            perfilProfesionalId: string | null;
        };
        /**
         * @description Solo dos estados. Un turno pasado no necesita uno propio: eso lo dice
         *     el reloj. "atendido" y "ausente" se agregarán el día que algo consuma
         *     ese dato —cobro, reputación o política de ausencias—.
         * @enum {string}
         */
        EstadoTurno: "reservado" | "cancelado";
        /**
         * @description Solo `inicio` y `motivo`. **No** se aceptan `fin` ni `modalidad`: los
         *     dos salen del hueco que se está tomando. Aceptarlos del cliente sería
         *     dejar que se invente un turno de tres horas en una agenda de cincuenta
         *     minutos, o una modalidad que el profesional no ofrece.
         */
        PeticionTurno: {
            /**
             * Format: date-time
             * @description Tiene que coincidir **exactamente** con el inicio de un hueco de
             *     `GET /api/v1/profesionales/{id}/huecos`. Cualquier otro valor es
             *     422: es la única validación de calendario del alta, y por eso
             *     arrastra sola el horario, los bloqueos, la anticipación mínima, el
             *     horizonte y el estado del profesional.
             */
            inicio: string;
            /** @description Opcional. Puede ser una cadena vacía. */
            motivo?: string;
        };
        Turno: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            profesionalId: string;
            /**
             * Format: uuid
             * @description Es el id del `Usuario` que reservó. No hay entidad paciente aparte.
             */
            pacienteId: string;
            /** Format: date-time */
            inicio: string;
            /**
             * Format: date-time
             * @description Copia del hueco al momento de reservar, no una lectura del horario
             *     actual. Si el profesional cambia el bloque después, este turno
             *     sigue diciendo lo que se pactó.
             */
            fin: string;
            modalidad: components["schemas"]["Modalidad"];
            estado: components["schemas"]["EstadoTurno"];
            motivo: string;
            /** Format: date-time */
            creadoEn: string;
            /** Format: date-time */
            canceladoEn: string | null;
            /**
             * Format: uuid
             * @description El `Usuario` que canceló. Comparándolo contra `pacienteId` se sabe
             *     si fue el paciente o el profesional.
             */
            canceladoPor: string | null;
        };
        ParteProfesional: {
            /** Format: uuid */
            id: string;
            nombre: string;
            apellido: string;
            slug: string;
            especialidad: components["schemas"]["Especialidad"];
        };
        /**
         * @description Sin email. El profesional necesita saber a quién atiende, no cómo
         *     contactarlo por fuera de la plataforma.
         */
        PartePaciente: {
            /** Format: uuid */
            id: string;
            nombre: string;
            apellido: string;
        };
        TurnoConProfesional: components["schemas"]["Turno"] & {
            profesional: components["schemas"]["ParteProfesional"];
        };
        TurnoConPaciente: components["schemas"]["Turno"] & {
            paciente: components["schemas"]["PartePaciente"];
        };
        /**
         * @description Cada turno viene con **la otra parte**: el profesional. Son dos formas y
         *     no una con los dos campos opcionales, para que el consumidor no tenga
         *     que acordarse de qué endpoint lo sacó.
         *
         *     Sin paginación: no es una colección paginada sino una ventana temporal,
         *     igual que `ListaBloqueos`. Incluye los cancelados — son parte del
         *     historial de las dos partes.
         */
        ListaTurnosDePaciente: {
            datos: components["schemas"]["TurnoConProfesional"][];
        };
        /**
         * @description Cada turno viene con el paciente. No filtra nada: este listado exige ser
         *     el dueño del perfil, así que el nombre de quien reservó es un dato al que
         *     ya se tiene derecho.
         */
        ListaTurnosDeProfesional: {
            datos: components["schemas"]["TurnoConPaciente"][];
        };
        /** @enum {string} */
        Especialidad: "psicologia" | "kinesiologia" | "odontologia";
        /** @enum {string} */
        Modalidad: "telemedicina" | "presencial" | "domicilio";
        /**
         * @description Si el profesional opera hoy en la plataforma
         * @enum {string}
         */
        Estado: "activo" | "inactivo";
        /**
         * @description Si su matrícula fue verificada contra el mundo real
         * @enum {string}
         */
        Verificacion: "pendiente" | "verificada" | "rechazada";
        Profesional: {
            /** Format: uuid */
            id: string;
            /** @example martin-gonzalez */
            slug: string;
            /** @example Martín */
            nombre: string;
            /** @example González */
            apellido: string;
            /**
             * @description Forma canónica. Distintas escrituras convergen acá.
             * @example MN 98234
             */
            matricula: string;
            especialidad: components["schemas"]["Especialidad"];
            bio: string;
            /**
             * Format: int64
             * @description Centavos. 1200000 son $12.000,00.
             * @example 1200000
             */
            precioConsultaCentavos: number;
            modalidades: components["schemas"]["Modalidad"][];
            /** @example CABA */
            zona: string;
            /**
             * @example [
             *       "OSDE",
             *       "Swiss Medical"
             *     ]
             */
            obrasSociales: string[];
            estado: components["schemas"]["Estado"];
            verificacion: components["schemas"]["Verificacion"];
            /** Format: date-time */
            creadoEn: string;
            /** Format: date-time */
            actualizadoEn: string;
            /** Format: date-time */
            dadoDeBajaEn: string | null;
            /**
             * @description Con cuánta anticipación mínima, en minutos, este profesional acepta
             *     reservas. El tope es una semana.
             * @default 120
             */
            anticipacionMinimaMin: number;
            /**
             * @description Cuántos días de agenda expone hacia adelante.
             * @default 60
             */
            horizonteDias: number;
        };
        PeticionProfesional: {
            nombre: string;
            apellido: string;
            /**
             * @description Acepta las formas reales del mercado: "MN 98.234", "M.N. 45321",
             *     "mn98234", "MP 12345". Se normaliza al guardar.
             * @example MN 98.234
             */
            matricula: string;
            especialidad: components["schemas"]["Especialidad"];
            bio?: string;
            /** Format: int64 */
            precioConsultaCentavos: number;
            modalidades: components["schemas"]["Modalidad"][];
            zona: string;
            obrasSociales?: string[];
            /**
             * @description Con cuánta anticipación mínima, en minutos, este profesional acepta
             *     reservas. El tope es una semana.
             * @default 120
             */
            anticipacionMinimaMin: number;
            /**
             * @description Cuántos días de agenda expone hacia adelante.
             * @default 60
             */
            horizonteDias: number;
        };
        ListaProfesionales: {
            datos: components["schemas"]["Profesional"][];
            paginacion: {
                /** @description Cuántos hay en total con esos filtros, no en la página */
                total: number;
                limite: number;
                desplazamiento: number;
            };
        };
        /** @enum {string} */
        DiaSemana: "lunes" | "martes" | "miercoles" | "jueves" | "viernes" | "sabado" | "domingo";
        HorarioSemanal: {
            diaSemana: components["schemas"]["DiaSemana"];
            /**
             * @description Hora de reloj, no un instante. "Atiendo de 9 a 13" significa las 9
             *     del reloj del profesional, siempre.
             * @example 09:00
             */
            desde: string;
            /** @example 13:00 */
            hasta: string;
            /**
             * @description Duración de cada sesión. Va en el bloque y no en el profesional
             *     porque una teleconsulta y una presencial no duran lo mismo.
             * @example 50
             */
            duracionMin: number;
            modalidad: components["schemas"]["Modalidad"];
        };
        ListaHorarios: {
            /**
             * @description Cuántos turnos futuros canceló esta operación por quedar fuera del
             *     horario nuevo. Siempre cero en el `GET`. El profesional se entera
             *     en el momento en que cambia su semana, no el día del turno.
             */
            turnosCancelados: number;
            horarios: components["schemas"]["HorarioSemanal"][];
        };
        BloqueoCreado: components["schemas"]["Bloqueo"] & {
            /**
             * @description Cuántos turnos futuros canceló este bloqueo. El profesional se
             *     entera en el momento de bloquear, no el día del turno.
             *
             *     Los turnos que ya ocurrieron no se tocan: un bloqueo puede
             *     cubrir fechas pasadas, pero reescribir una consulta que
             *     efectivamente pasó borraría su registro.
             */
            turnosCancelados: number;
        };
        Bloqueo: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            /** @description Opcional. Puede ser una cadena vacía. */
            motivo: string;
            /** Format: date-time */
            creadoEn: string;
        };
        PeticionBloqueo: {
            /** Format: date-time */
            desde: string;
            /** Format: date-time */
            hasta: string;
            motivo?: string;
        };
        ListaBloqueos: {
            datos: components["schemas"]["Bloqueo"][];
        };
        Hueco: {
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fin: string;
            modalidad: components["schemas"]["Modalidad"];
        };
        ListaHuecos: {
            datos: components["schemas"]["Hueco"][];
            /**
             * @description El rango que de verdad se usó, que puede ser menor al pedido si el
             *     horizonte del profesional lo recortó.
             */
            rango: {
                /** Format: date */
                desde: string;
                /** Format: date */
                hasta: string;
            };
        };
        PeticionHorarios: {
            horarios: {
                diaSemana: components["schemas"]["DiaSemana"];
                /** @example 09:00 */
                desde: string;
                /** @example 13:00 */
                hasta: string;
                /** @example 50 */
                duracionMin: number;
                modalidad: components["schemas"]["Modalidad"];
            }[];
        };
        /** @description Detalles del problema según RFC 7807 */
        Problema: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Presente solo en errores de validación */
            errores?: {
                campo: string;
                mensaje: string;
            }[];
        };
    };
    responses: {
        /** @description JSON malformado o parámetro con formato inválido */
        PeticionInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description No existe */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Choque con un registro existente: la matrícula ya está tomada por otro
         *     profesional, o la cuenta ya tiene un perfil profesional.
         */
        Conflicto: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description No hay sesión, o la que hay venció. Distinto del 403: acá el servidor
         *     no sabe quién sos.
         */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Hay sesión, pero el recurso es de otro. Solo el dueño de un perfil
         *     puede modificarlo, cargarle horarios o bloquearle la agenda.
         */
        NoAutorizado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description El email o la contraseña no son correctos. La respuesta es idéntica en
         *     los dos casos: distinguirlos revelaría qué direcciones están
         *     registradas.
         */
        CredencialesInvalidas: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Ya existe una cuenta con ese email */
        EmailEnUso: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description El hueco ya fue reservado por otro paciente, o el paciente ya tiene
         *     otro turno activo a esa hora con otro profesional.
         */
        TurnoNoDisponible: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description El cuerpo tiene que llegar con `Content-Type: application/json`. La
         *     regla es parte de la defensa contra CSRF: un formulario de otro sitio
         *     solo puede mandar `form-urlencoded`, `multipart` o `text/plain`.
         */
        TipoDeContenidoInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description El cuerpo de la petición supera el límite permitido */
        CuerpoDemasiadoGrande: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description JSON válido pero datos inválidos. Distinto de 400: "entendí perfecto
         *     y está mal" es otro problema que "no entiendo lo que mandaste".
         */
        ValidacionFallida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"] & Record<string, never>;
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
